FROM nginx:alpine
COPY *.html *.css /usr/share/nginx/html
COPY pictureskon /usr/share/nginx/html/pictureskon
COPY picturesoform /usr/share/nginx/html/picturesoform
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
